### ISSUE TITLE
Can't publish elemental page

### ISSUE THREAD

**Issue by maxime-rainville** [dnadesign/silverstripe-elemental-userforms#37] opened 2018-12-10 04:13 UTC
# Affected  version
* SilverStripe 4.3-RC1
* dnadesign/silverstripe-elemental 4.0.0-beta1
* dnadesign/silverstripe-elemental-userforms 3.0.0-beta1
* with the Kitchen sink installed

# Description
If you try to publish a content block page with a user form block, you get a 500 internal server error.

```
[Warning] Invalid argument supplied for foreach()
POST /admin/pages/edit/EditForm/17/

Line 232 in /home/maxime/Projects/ss43rc/vendor/dnadesign/silverstripe-elemental/src/Forms/ElementalAreaField.php
```

# Steps to reproduce
* Create a elemental page
* Add a user form block.
* Add a title and a single text field to you block.
* Try publishing your page.

https://youtu.be/aYuDTgeFO0Y

**Comment by robbieaverill** [comment] 2018-12-12 14:39
I suspect there'll be a workaround for this involving a combination of page publishing and flushing, but haven't tested yet

**Comment by robbieaverill** [comment] 2018-12-17 16:22
I can reproduce this with CWP 2.2.0 using recipe-content-blocks 2.1.0 (containing elemental 4.0.0-beta1).

I can't reproduce this with CWP 2.2.x-dev using recipe-content-blocks 2.1.x-dev (containing elemental 4.0.x-dev).

Looks like this was fixed with https://github.com/dnadesign/silverstripe-elemental/pull/498. It's a shame it didn't make the cutoff for CWP 2.2.0 stable, but such is the reality of audited code releases. We'll likely be releasing a new version of `silverstripe/recipe-content-blocks` soon which will contain elemental 4.0.0 stable, and can be used with CWP 2.2.0 as well.

**Closed by robbieaverill** 2018-12-17 16:22 UTC
Labels: affects/v4, change/patch, effort/easy, impact/high, type/UX, type/bug
