### ISSUE TITLE
BUG: multiple forms on one page

### ISSUE THREAD

**Issue by rasstislav** [dnadesign/silverstripe-elemental-userforms#82] opened 2023-09-22 10:11 UTC
Hello,

I have this BUG: If I use multiple forms on one page and submit one of them, they all appear as submitted.

I see the problem in [evaluating whether the form has been sent](https://github.com/dnadesign/silverstripe-elemental-userforms/blob/9ab97a3bd01272e169713e0d6232223c148a254d/src/Model/ElementForm.php#L37-L39) (condition for current element is missing).

![image](https://github.com/dnadesign/silverstripe-elemental-userforms/assets/9253113/47b59cd8-2888-4da0-a6c4-335089069b99)

![image](https://github.com/dnadesign/silverstripe-elemental-userforms/assets/9253113/d620cd2e-0dd2-4548-8dfb-80987f4b8f65)

**Comment by GuySartorelli** [comment] 2023-09-25 01:57
Thank you for submitting this report and for looking into the root cause - would you like to submit a pull request implementing a fix?

**Comment by michalkleiner** [comment] 2023-09-25 02:13
Duplicate of https://github.com/dnadesign/silverstripe-elemental-userforms/issues/50

**Comment by GuySartorelli** [comment] 2023-09-25 02:17
Ahh, cool. I'll close this duplicate then.

**Closed as not planned by GuySartorelli** 2023-09-25 02:17 UTC
Labels: type/bug
