### ISSUE TITLE
Form submission issue

### ISSUE THREAD

**Issue by Thiyagarajantender** [dnadesign/silverstripe-elemental-userforms#59] opened 2022-04-01 07:09 UTC
Getting below error when use form inside list block.

Fatal error: Element $id not found for this page in F:\xampp7\htdocs\4es-git\vendor\dnadesign\silverstripe-elemental\src\Extensions\ElementalContentControllerExtension.php on line 47

Notice: Undefined index: args in F:\xampp7\htdocs\4es-git\vendor\silverstripe\framework\src\Dev\Backtrace.php on line 216

Notice: Trying to access array offset on value of type null in F:\xampp7\htdocs\4es-git\vendor\silverstripe\framework\src\Dev\Backtrace.php on line 216

Please adviceto overcome this issue

**Comment by GuySartorelli** [comment] 2023-10-12 03:48
Closing as a duplicate of https://github.com/dnadesign/silverstripe-elemental-userforms/issues/27

**Closed as not planned by GuySartorelli** 2023-10-12 03:48 UTC
Labels: type/bug
